[package]
name = "magick-resize"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
eyre = "0.6.12"
glob = "0.3.1"
indicatif = "0.17.8"
infer = "0.16.0"
pathdiff = "0.2.1"
